# Generated by Django 4.1 on 2023-04-18 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agrivisionapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="signup", name="branch",),
        migrations.RemoveField(model_name="signup", name="role",),
    ]
